<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Version>0.1.0</Version>
    <NeutralLanguage>ru-RU</NeutralLanguage>
  </PropertyGroup>

</Project>
